app <- ShinyDriver$new("../../")
app$snapshotInit("basic_select_only")

app$snapshot()
app$setInputs(axisXSel = "Sepal.Width")
app$snapshot()
app$setInputs(axisXSel = "Petal.Length")
app$snapshot()
app$setInputs(axisXSel = "Petal.Width")
app$snapshot()
app$setInputs(axisXSel = "Sepal.Length")
app$setInputs(axisYSel = "Sepal.Length")
app$snapshot()
app$setInputs(axisYSel = "Petal.Length")
app$snapshot()
app$setInputs(axisYSel = "Petal.Width")
app$snapshot()
