app <- ShinyDriver$new("../../")
app$snapshotInit("example1_test")

app$snapshot()
app$setInputs(colorBySel = "Sepal.Width")
app$snapshot()
app$setInputs(shapeBySel = "Petal.Width")
app$snapshot()
app$setInputs(axisXSel = "Sepal.Width")
app$snapshot()
app$setInputs(axisXSel = "Petal.Length")
app$snapshot()
app$setInputs(axisXSel = "Petal.Width")
app$snapshot()
app$setInputs(axisYSel = "Sepal.Length")
app$snapshot()
app$setInputs(axisYSel = "Petal.Length")
app$snapshot()
app$setInputs(axisYSel = "Petal.Width")
app$snapshot()
app$setInputs(axisYSel = "Sepal.Length")
app$snapshot()
app$setInputs(colorBySel = "Petal.Length")
app$snapshot()
app$setInputs(colorBySel = "Petal.Width")
app$snapshot()
app$setInputs(shapeBySel = "Sepal.Length")
app$setInputs(shapeBySel = "Sepal.Width")
app$snapshot()
app$setInputs(shapeBySel = "Petal.Length")
app$snapshot()
