app <- ShinyDriver$new("../../")
app$snapshotInit("select_and_coloring_and_shaping")

app$setInputs(colorBySel = "Sepal.Length")
app$setInputs(shapeBySel = "Sepal.Length")
app$snapshot()
app$setInputs(colorBySel = "Sepal.Width")
app$snapshot()
app$setInputs(colorBySel = "Petal.Length")
app$snapshot()
app$setInputs(colorBySel = "Petal.Width")
app$snapshot()
app$setInputs(colorBySel = "Sepal.Length")
app$setInputs(shapeBySel = "Sepal.Width")
app$snapshot()
app$setInputs(shapeBySel = "Petal.Length")
app$snapshot()
app$setInputs(shapeBySel = "Petal.Width")
app$snapshot()
