# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
cache: packages
bioc_packages: limma
r_packages:
  - covr
  - canvasXpress.data
if: |
  branch IN (master, cran) AND \
  repo = cb4ds/canvasXpress
after_success:
  - Rscript -e 'library(covr); codecov(quiet = FALSE)'
latex: false
