# Notes:
# - Docker containers with R, etc. provided by rocker.  See <https://hub.docker.com/r/rocker/verse>.
# - Builds attempted for 4.0.5, 4.2.3, and the *latest* R edition supported by rocker.

version: 2.1
jobs:
  Build-for-r4_0_5:
    docker:
      - image: rocker/verse:4.0.5

    steps:
      - checkout
      - run:
          name: Review checkout
          command: ls -la

      - run:
          name: Install Linux dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -yq texlive-fonts-recommended
            sudo apt-get install -yq texlive-fonts-extra

      - run:
          name: Install R dependencies
          command: |
            R -e 'install.packages("BiocManager")'
            R -e 'BiocManager::install(c("limma"))'
            R -e 'BiocManager::install(c("survminer"))'
            R -e 'install.packages("covr")'
            R -e 'install.packages("canvasXpress.data")'
            R -e 'install.packages("DT")'
            R -e 'install.packages("S7")'

      - run:
          name: Session information and installed package versions
          command: |
            Rscript -e 'sessionInfo()'
            Rscript -e 'installed.packages()[, c("Package", "Version")]'
            Rscript -e 'rmarkdown::pandoc_version()'

      - run:
          name: Build package
          command: R CMD build .

      - run:
          name: Check coverage
          command: Rscript -e 'library(covr); codecov(quiet = FALSE)'

      - run:
          name: Check package
          command: |
            # Install suggested packages
            R -e 'install.packages("png")'
            # Perform package check
            R CMD check *tar.gz

  Build-for-r4_3_3:
    docker:
      - image: rocker/verse:4.3.3

    steps:
      - checkout
      - run:
          name: Review checkout
          command: ls -la

      - run:
          name: Install Linux dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -yq texlive-fonts-recommended
            sudo apt-get install -yq texlive-fonts-extra

      - run:
          name: Install R dependencies
          command: |
            R -e 'install.packages("BiocManager")'
            R -e 'BiocManager::install(c("limma"))'
            R -e 'BiocManager::install(c("survminer"))'
            R -e 'install.packages("covr")'
            R -e 'install.packages("canvasXpress.data")'
            R -e 'install.packages("DT")'
            R -e 'install.packages("S7")'

      - run:
          name: Session information and installed package versions
          command: |
            Rscript -e 'sessionInfo()'
            Rscript -e 'installed.packages()[, c("Package", "Version")]'
            Rscript -e 'rmarkdown::pandoc_version()'

      - run:
          name: Build package
          command: R CMD build .

      - run:
          name: Check coverage
          command: Rscript -e 'library(covr); codecov(quiet = FALSE)'

      - run:
          name: Check package
          command: |
            # Install suggested packages
            R -e 'install.packages("png")'
            # Perform package check
            R CMD check *tar.gz

  Build-for-r4_4_3:
    docker:
      - image: rocker/verse:4.4.3

    steps:
      - checkout
      - run:
          name: Review checkout
          command: ls -la

      - run:
          name: Install Linux dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -yq texlive-fonts-recommended
            sudo apt-get install -yq texlive-fonts-extra

      - run:
          name: Install R dependencies
          command: |
            R -e 'install.packages("BiocManager")'
            R -e 'BiocManager::install(c("limma"))'
            R -e 'BiocManager::install(c("survminer"))'
            R -e 'install.packages("covr")'
            R -e 'install.packages("canvasXpress.data")'
            R -e 'install.packages("DT")'
            R -e 'install.packages("S7")'

      - run:
          name: Session information and installed package versions
          command: |
            Rscript -e 'sessionInfo()'
            Rscript -e 'installed.packages()[, c("Package", "Version")]'
            Rscript -e 'rmarkdown::pandoc_version()'

      - run:
          name: Build package
          command: R CMD build .

      - run:
          name: Check coverage
          command: Rscript -e 'library(covr); codecov(quiet = FALSE)'

      - run:
          name: Check package
          command: |
            # Install suggested packages
            R -e 'install.packages("png")'
            # Perform package check
            R CMD check *tar.gz

  Build-for-rLATEST:
    docker:
      - image: rocker/verse:latest

    steps:
      - checkout
      - run:
          name: Review checkout
          command: ls -la

      - run:
          name: Install Linux dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -yq texlive-fonts-recommended
            sudo apt-get install -yq texlive-fonts-extra

      - run:
          name: Install R dependencies
          command: |
            R -e 'install.packages("BiocManager")'
            R -e 'BiocManager::install(c("limma"))'
            R -e 'BiocManager::install(c("survminer"))'
            R -e 'install.packages("covr")'
            R -e 'install.packages("canvasXpress.data")'
            R -e 'install.packages("DT")'
            R -e 'install.packages("S7")'

      - run:
          name: Session information and installed package versions
          command: |
            Rscript -e 'sessionInfo()'
            Rscript -e 'installed.packages()[, c("Package", "Version")]'
            Rscript -e 'rmarkdown::pandoc_version()'

      - run:
          name: Build package
          command: R CMD build .

      - run:
          name: Check coverage
          command: Rscript -e 'library(covr); codecov(quiet = FALSE)'

      - run:
          name: Check package
          command: |
            # Install suggested packages
            R -e 'install.packages("png")'
            # Perform package check
            R CMD check *tar.gz

workflows:
  version: 2
  Prepare-All-R-Editions:
    jobs:
      - Build-for-r4_0_5
      - Build-for-r4_3_3
      - Build-for-r4_4_3
      - Build-for-rLATEST
